server:
  port: 8080
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/eat
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: ${{ secrets.EC2_HOST }}
    username: root
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comments: true # show jpql in console
logging:
  level:
    org.hibernate.SQL: debug